### ISSUE TITLE
Works on localhost but not after deployed with 'npm run generate'

### ISSUE THREAD

**Issue by jpnothard** [oktadeveloper/okta-universals-apps-with-nuxt#8]
Hi,

Thanks for this example, very well explained.

I have found that after I build the example with `npm run generare` and upload it to a Netlify or AWS server it gets stuck in some kind of redirect/page refresh loop.

Everything works great on my localhost just not anywhere else.

If you are able to help great, even if its an idea of what i could be missing to make this work properly.

Thanks in advance.

**Comment by andymarch** [comment]
Can you confirm where the redirect loop occurs? I can reproduce (on Netlify) a strange redirect loop if try to reach the protected pages. It might be because the result of the mock status service in progress.vue is targeting a localhost resource. It's looking a little bit more fundamental than that, I'll try to take a more detailed look tomorrow.

It's worth noting that the official auth module for Nuxt (https://github.com/nuxt-community/auth-module) has now been fixed so this should be able to correctly handle OIDC now. So a revisit to this article is probably needed.

**Comment by jpnothard** [comment]
@andymarch Thanks for taking a look. I can confirm that it is only the protected pages that are causing the redirect loop.

**Comment by andymarch** [comment]
I've reproduced the behaviour locally with the following steps:
`npm generate
http-server ./dist`
This is the same outcome as if you had seen serving the dist from Netlify or an S3 bucket.

You are encountering this because the application is not entirely statically generated, with Nuxt you have both a client and server component. The Nuxt OAuth package contains a server middleware which is performing an essential part of the OAuth handshake as it provides a confidential client with which to perform the back channel part of the exchange. From looking into the the oauth middleware It looks like the route setup to listen at /auth/login is serverside and it gets into a redirect loop when it can't reach it. I see you have [an issue](https://github.com/SohoHouse/nuxt-oauth/issues/46) open on the nuxt-oauth project also, I'm watching there too if i can help.

You could maybe try hosting with a service like Heroku where you can run the server component also.
